# Generated by Django 5.1.7 on 2025-04-07 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('conclusion', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=7)),
                ('end_date', models.CharField(max_length=7)),
                ('position', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True, null=True)),
                ('figma', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=7)),
                ('end_date', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=100)),
                ('description', models.JSONField(default=list)),
                ('location', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(related_name='experiences', to='wonderland.project')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=7)),
                ('end_date', models.CharField(max_length=7)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('projects', models.ManyToManyField(related_name='educations', to='wonderland.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wonderland.project')),
            ],
        ),
    ]
