# Generated by Django 5.1.7 on 2025-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderland', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='projects',
            field=models.ManyToManyField(related_name='educations', to='wonderland.project'),
        ),
        migrations.AddField(
            model_name='experience',
            name='projects',
            field=models.ManyToManyField(related_name='experiences', to='wonderland.project'),
        ),
    ]
