# Generated by Django 5.1.7 on 2025-03-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wonderland', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=100)),
                ('description', models.JSONField(default=list)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='message',
        ),
    ]
